#!/bin/bash

###############################################################################
# ChatSDK - Create Chat App
# Generate a customized chat UI from the react-chat-huly template
#
# Usage:
#   ./create-chat-app.sh my-chat-app
#   ./create-chat-app.sh my-chat-app --api-url=https://api.mysite.com
###############################################################################

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
DIM='\033[2m'
NC='\033[0m'

# Default values
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TEMPLATE_DIR="$SCRIPT_DIR/examples/react-chat-huly"
API_URL="http://localhost:5500"
WS_URL="ws://localhost:8001/connection/websocket"

# Parse arguments
APP_NAME=""
for arg in "$@"; do
    case $arg in
        --api-url=*)
            API_URL="${arg#*=}"
            shift
            ;;
        --ws-url=*)
            WS_URL="${arg#*=}"
            shift
            ;;
        --help|-h)
            echo "Usage: ./create-chat-app.sh <app-name> [options]"
            echo ""
            echo "Options:"
            echo "  --api-url=URL    API server URL (default: http://localhost:5500)"
            echo "  --ws-url=URL     WebSocket URL (default: ws://localhost:8001/connection/websocket)"
            echo ""
            echo "Examples:"
            echo "  ./create-chat-app.sh my-chat"
            echo "  ./create-chat-app.sh my-chat --api-url=https://api.example.com"
            exit 0
            ;;
        *)
            if [[ -z "$APP_NAME" ]]; then
                APP_NAME="$arg"
            fi
            ;;
    esac
done

# Validate app name
if [[ -z "$APP_NAME" ]]; then
    echo -e "${RED}Error: App name is required${NC}"
    echo ""
    echo "Usage: ./create-chat-app.sh <app-name>"
    echo "Example: ./create-chat-app.sh my-chat-app"
    exit 1
fi

# Sanitize app name (lowercase, hyphens only)
SAFE_NAME=$(echo "$APP_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g' | sed 's/--*/-/g')
OUTPUT_DIR="$SCRIPT_DIR/../$SAFE_NAME"

# Check if directory exists
if [[ -d "$OUTPUT_DIR" ]]; then
    echo -e "${RED}Error: Directory '$SAFE_NAME' already exists${NC}"
    echo "Choose a different name or remove the existing directory."
    exit 1
fi

# Check template exists
if [[ ! -d "$TEMPLATE_DIR" ]]; then
    echo -e "${RED}Error: Template not found at $TEMPLATE_DIR${NC}"
    exit 1
fi

echo -e "${CYAN}"
cat << "EOF"
   _____ _           _   _____ _____  _  __
  / ____| |         | | / ____|  __ \| |/ /
 | |    | |__   __ _| || (___ | |  | | ' /
 | |    | '_ \ / _` | | \___ \| |  | |  <
 | |____| | | | (_| | | ____) | |__| | . \
  \_____|_| |_|\__,_|_||_____/|_____/|_|\_\

        CREATE CHAT APP
EOF
echo -e "${NC}"
echo ""

echo -e "${BLUE}Creating chat app: ${BOLD}$SAFE_NAME${NC}"
echo ""

###############################################################################
# Copy Template
###############################################################################

echo -e "${BLUE}Copying template...${NC}"

cp -r "$TEMPLATE_DIR" "$OUTPUT_DIR"

echo -e "${GREEN}Template copied${NC}"

###############################################################################
# Customize package.json
###############################################################################

echo -e "${BLUE}Customizing configuration...${NC}"

# Update package.json
cat > "$OUTPUT_DIR/package.json.tmp" << EOF
{
  "name": "$SAFE_NAME",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "tsc -b && vite build",
    "lint": "eslint .",
    "preview": "vite preview"
  },
  "dependencies": {
EOF

# Extract dependencies from original package.json (skip name, version, etc)
grep -A 1000 '"dependencies"' "$OUTPUT_DIR/package.json" | tail -n +2 | head -n -2 >> "$OUTPUT_DIR/package.json.tmp"

cat >> "$OUTPUT_DIR/package.json.tmp" << EOF
  },
  "devDependencies": {
EOF

grep -A 1000 '"devDependencies"' "$OUTPUT_DIR/package.json" | tail -n +2 | head -n -1 >> "$OUTPUT_DIR/package.json.tmp"

echo "}" >> "$OUTPUT_DIR/package.json.tmp"

mv "$OUTPUT_DIR/package.json.tmp" "$OUTPUT_DIR/package.json"

###############################################################################
# Create Environment File
###############################################################################

cat > "$OUTPUT_DIR/.env" << EOF
# ChatSDK Configuration
# Generated by create-chat-app.sh

VITE_API_URL=$API_URL
VITE_WS_URL=$WS_URL

# Get your API key from ChatSDK admin or credentials/secrets.json
VITE_APP_API_KEY=your-api-key-here
EOF

cat > "$OUTPUT_DIR/.env.example" << EOF
# ChatSDK Configuration Example
VITE_API_URL=http://localhost:5500
VITE_WS_URL=ws://localhost:8001/connection/websocket
VITE_APP_API_KEY=your-api-key-here
EOF

###############################################################################
# Create README
###############################################################################

cat > "$OUTPUT_DIR/README.md" << EOF
# $APP_NAME

A chat application built with ChatSDK.

## Quick Start

1. Install dependencies:
\`\`\`bash
npm install
\`\`\`

2. Configure your API key in \`.env\`:
\`\`\`
VITE_API_URL=$API_URL
VITE_WS_URL=$WS_URL
VITE_APP_API_KEY=your-api-key-here
\`\`\`

3. Start development server:
\`\`\`bash
npm run dev
\`\`\`

4. Open http://localhost:5173 in your browser.

## Getting Your API Key

If you ran \`./instant-setup.sh\`, your API key is in:
- \`credentials/secrets.json\`
- \`credentials/QUICKSTART.md\`

Or create a token manually:
\`\`\`bash
curl -X POST $API_URL/tokens \\
  -H "X-API-Key: YOUR_API_KEY" \\
  -H "Content-Type: application/json" \\
  -d '{"userId": "user-1", "name": "Test User"}'
\`\`\`

## Build for Production

\`\`\`bash
npm run build
\`\`\`

Built files will be in the \`dist/\` folder.

## Customization

- **Colors/Theme**: Edit \`tailwind.config.js\`
- **Components**: Edit files in \`src/components/\`
- **API Client**: Edit \`src/lib/api-client.ts\`

## Learn More

- [ChatSDK Documentation](./delivery-package/docs/)
- [API Reference](./delivery-package/docs/API_REFERENCE.md)
- [Authentication Guide](./delivery-package/docs/AUTHENTICATION.md)
EOF

###############################################################################
# Clean up unnecessary files
###############################################################################

rm -rf "$OUTPUT_DIR/.git" 2>/dev/null || true
rm -rf "$OUTPUT_DIR/node_modules" 2>/dev/null || true
rm -f "$OUTPUT_DIR/package-lock.json" 2>/dev/null || true

###############################################################################
# Create .gitignore
###############################################################################

cat > "$OUTPUT_DIR/.gitignore" << EOF
# Dependencies
node_modules/

# Build output
dist/

# Environment files
.env
.env.local
.env.*.local

# IDE
.vscode/
.idea/

# OS
.DS_Store
Thumbs.db

# Logs
*.log
npm-debug.log*
EOF

echo -e "${GREEN}Configuration complete${NC}"
echo ""

###############################################################################
# Final Output
###############################################################################

echo -e "${GREEN}Chat app created successfully!${NC}"
echo ""
echo -e "${CYAN}Location:${NC} $OUTPUT_DIR"
echo ""
echo -e "${CYAN}Next steps:${NC}"
echo ""
echo -e "  1. ${BOLD}cd $SAFE_NAME${NC}"
echo ""
echo -e "  2. ${BOLD}npm install${NC}"
echo ""
echo -e "  3. Edit ${BOLD}.env${NC} with your API key:"
echo -e "     ${DIM}VITE_APP_API_KEY=your-api-key-here${NC}"
echo ""
echo -e "  4. ${BOLD}npm run dev${NC}"
echo ""
echo -e "  5. Open ${GREEN}http://localhost:5173${NC}"
echo ""
echo -e "${CYAN}Configuration:${NC}"
echo -e "  API URL:       ${YELLOW}$API_URL${NC}"
echo -e "  WebSocket URL: ${YELLOW}$WS_URL${NC}"
echo ""

# If instant-setup was run, show the API key
if [[ -f "$SCRIPT_DIR/credentials/secrets.json" ]]; then
    API_KEY=$(grep -o '"api_key": "[^"]*"' "$SCRIPT_DIR/credentials/secrets.json" | head -1 | cut -d'"' -f4)
    if [[ -n "$API_KEY" ]]; then
        echo -e "${CYAN}Your API Key (from instant-setup):${NC}"
        echo -e "  ${YELLOW}$API_KEY${NC}"
        echo ""

        # Also update the .env file with the actual key
        sed -i.bak "s/your-api-key-here/$API_KEY/" "$OUTPUT_DIR/.env" 2>/dev/null || true
        rm -f "$OUTPUT_DIR/.env.bak" 2>/dev/null || true
        echo -e "${DIM}(API key has been added to .env)${NC}"
        echo ""
    fi
fi

echo -e "${GREEN}Happy coding!${NC}"
echo ""
