/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guideSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'QUICK_START',
      label: 'Quick Start',
    },
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'guides/getting-started',
        'guides/react',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/features',
        },
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        {
          type: 'autogenerated',
          dirName: 'guides/advanced',
        },
      ],
    },
    {
      type: 'doc',
      id: 'guides/troubleshooting',
      label: 'Troubleshooting',
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'API_REFERENCE',
        'TOKEN_GENERATION_GUIDE',
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Enterprise',
      items: [
        {
          type: 'autogenerated',
          dirName: 'enterprise',
        },
      ],
    },
    {
      type: 'category',
      label: 'HIPAA Compliance',
      items: [
        {
          type: 'autogenerated',
          dirName: 'hipaa-compliance',
        },
      ],
    },
  ],
};

module.exports = sidebars;
