import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';
import type { Template } from './templates.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

interface ScaffoldOptions {
  projectName: string;
  projectPath: string;
  template: Template;
  useTypeScript: boolean;
  includeExamples: boolean;
}

export async function scaffoldProject(options: ScaffoldOptions): Promise<void> {
  const { projectPath, template, useTypeScript, includeExamples } = options;

  // Create project directory
  await fs.ensureDir(projectPath);

  // Copy template files
  const templatePath = path.join(__dirname, '..', 'templates', template);
  if (await fs.pathExists(templatePath)) {
    await fs.copy(templatePath, projectPath);
  } else {
    // Template doesn't exist yet
    throw new Error(
      `Template "${template}" is not available yet.\n\n` +
      `Available templates:\n` +
      `  - nextjs-app-router (Next.js + App Router)\n` +
      `  - minimal (SDK only)\n\n` +
      `Coming soon: vite-react, react-native-expo, express-react`
    );
  }

  // Remove TypeScript files if JavaScript selected
  if (!useTypeScript) {
    await convertToJavaScript(projectPath);
  }

  // Remove examples if not needed
  if (!includeExamples) {
    await removeExamples(projectPath, template);
  }

  // Update package.json with project name
  const packageJsonPath = path.join(projectPath, 'package.json');
  if (await fs.pathExists(packageJsonPath)) {
    const packageJson = await fs.readJSON(packageJsonPath);
    packageJson.name = options.projectName;
    await fs.writeJSON(packageJsonPath, packageJson, { spaces: 2 });
  }

  // Create .env.local with defaults
  const envPath = path.join(projectPath, '.env.local');
  const envContent = `# ChatSDK Configuration
# Auto-generated by create-chatsdk-app

# API Configuration (development)
NEXT_PUBLIC_CHATSDK_API_KEY=dev-api-key
NEXT_PUBLIC_CHATSDK_API_URL=http://localhost:5500
NEXT_PUBLIC_CHATSDK_WS_URL=ws://localhost:8001/connection/websocket

# Development Mode
NEXT_PUBLIC_CHATSDK_DEBUG=true

# Docker Services (auto-configured)
DATABASE_URL=postgresql://chatsdk:chatsdk_dev@localhost:5432/chatsdk
REDIS_URL=redis://localhost:6379
CENTRIFUGO_URL=http://localhost:8001
CENTRIFUGO_API_KEY=chatsdk-api-key-change-in-production
CENTRIFUGO_TOKEN_SECRET=chatsdk-dev-secret-key-change-in-production
S3_ENDPOINT=http://localhost:9000
S3_ACCESS_KEY_ID=chatsdk
S3_SECRET_ACCESS_KEY=chatsdk_dev_123
MEILISEARCH_HOST=http://localhost:7700
MEILISEARCH_API_KEY=chatsdk_dev_key
`;

  await fs.writeFile(envPath, envContent);

  // Add .env.local to .gitignore
  const gitignorePath = path.join(projectPath, '.gitignore');
  let gitignoreContent = '';
  if (await fs.pathExists(gitignorePath)) {
    gitignoreContent = await fs.readFile(gitignorePath, 'utf-8');
  }
  if (!gitignoreContent.includes('.env.local')) {
    gitignoreContent += '\n# Environment variables\n.env.local\n.env.*.local\n';
    await fs.writeFile(gitignorePath, gitignoreContent);
  }
}

async function createMinimalTemplate(options: ScaffoldOptions): Promise<void> {
  const { projectPath, projectName } = options;

  // Create package.json
  const packageJson = {
    name: projectName,
    version: '0.1.0',
    private: true,
    type: 'module',
    scripts: {
      dev: 'node index.js',
    },
    dependencies: {
      '@chatsdk/core': 'latest',
    },
  };

  await fs.writeJSON(path.join(projectPath, 'package.json'), packageJson, { spaces: 2 });

  // Create index.js with minimal example
  const indexContent = `import { ChatSDK } from '@chatsdk/core';

async function main() {
  // Connect to ChatSDK (development mode - no API key required)
  const client = await ChatSDK.connectDevelopment({
    userId: 'demo-user',
    displayName: 'Demo User',
    apiUrl: 'http://localhost:5500',
    wsUrl: 'ws://localhost:8001/connection/websocket',
    debug: true,
  });

  console.log('✅ Connected to ChatSDK!');

  // Listen for new messages
  client.on('message.new', (message) => {
    console.log('New message:', message.text);
  });

  // Create a channel
  const channel = await client.createChannel({
    type: 'messaging',
    id: 'general',
    name: 'General',
  });

  console.log('Created channel:', channel.name);

  // Send a message
  const message = await client.sendMessage({
    channelId: channel.id,
    text: 'Hello from ChatSDK! 🚀',
  });

  console.log('Sent message:', message.text);
  console.log('\\n🎉 Success! ChatSDK is working.');
  console.log('Next steps:');
  console.log('- Edit index.js to customize your chat app');
  console.log('- Check out https://docs.chatsdk.dev for more examples');
}

main().catch(console.error);
`;

  await fs.writeFile(path.join(projectPath, 'index.js'), indexContent);

  // Create README
  const readmeContent = `# ${projectName}

A minimal ChatSDK application.

## Quick Start

1. Start Docker services (if not already running):
   \`\`\`bash
   docker compose up -d
   \`\`\`

2. Run the app:
   \`\`\`bash
   npm run dev
   \`\`\`

## Learn More

- [ChatSDK Documentation](https://docs.chatsdk.dev)
- [API Reference](https://docs.chatsdk.dev/api)
- [Examples](https://github.com/chatsdk/examples)
`;

  await fs.writeFile(path.join(projectPath, 'README.md'), readmeContent);

  // Create .gitignore
  const gitignoreContent = `node_modules/
.env.local
.env.*.local
dist/
*.log
`;

  await fs.writeFile(path.join(projectPath, '.gitignore'), gitignoreContent);
}

async function convertToJavaScript(projectPath: string): Promise<void> {
  // Remove TypeScript config
  const tsConfigPath = path.join(projectPath, 'tsconfig.json');
  if (await fs.pathExists(tsConfigPath)) {
    await fs.remove(tsConfigPath);
  }

  // Recursively rename .ts/.tsx files to .js/.jsx
  async function renameFiles(dir: string): Promise<void> {
    const entries = await fs.readdir(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);

      if (entry.isDirectory()) {
        await renameFiles(fullPath);
      } else if (entry.name.endsWith('.ts') && !entry.name.endsWith('.d.ts')) {
        await fs.rename(fullPath, fullPath.replace('.ts', '.js'));
      } else if (entry.name.endsWith('.tsx')) {
        await fs.rename(fullPath, fullPath.replace('.tsx', '.jsx'));
      }
    }
  }

  await renameFiles(projectPath);
}

async function removeExamples(projectPath: string, template: Template): Promise<void> {
  // Template-specific example paths to remove
  const examplePaths: Record<Template, string[]> = {
    'nextjs-app-router': [
      'app/(chat)',
      'components/chat',
    ],
    'vite-react': [
      'src/pages',
      'src/components/chat',
    ],
    'react-native-expo': [
      'app/(tabs)',
      'components/chat',
    ],
    'express-react': [
      'client/src/pages',
      'client/src/components/chat',
    ],
    minimal: [],
  };

  const paths = examplePaths[template];
  for (const examplePath of paths) {
    const fullPath = path.join(projectPath, examplePath);
    if (await fs.pathExists(fullPath)) {
      await fs.remove(fullPath);
    }
  }

  // Create minimal placeholder files for Next.js
  if (template === 'nextjs-app-router') {
    const appPath = path.join(projectPath, 'app/page.tsx');
    await fs.ensureDir(path.dirname(appPath));
    await fs.writeFile(
      appPath,
      `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">ChatSDK App</h1>
      <p className="mt-4 text-gray-600">Ready to build your chat experience!</p>
    </main>
  );
}
`
    );
  }
}
